services:
  ##############################################################################
  # DEVELOPMENT CONTAINER SERVICE                                              #
  ##############################################################################
  devcontainer:
    # --------------------------------------------------------------------------
    # IMAGE
    # --------------------------------------------------------------------------
    # Specifies the container image and exact digest used for the
    # development environment.
    image: "mcr.microsoft.com/devcontainers/base@sha256:55126de3b3e113096201055951b4cb717900bafb379c59dcbada65c49cd7ce22" # jammy

    # --------------------------------------------------------------------------
    # TTY
    # --------------------------------------------------------------------------
    # When set to true, this directive allocates a pseudo-TTY. This is
    # required for processes that remain active and allow for interactive
    # shell sessions.
    tty: true

    # --------------------------------------------------------------------------
    # VOLUMES
    # --------------------------------------------------------------------------
    # Defines the mount points between the host system and the container.
    volumes:
      - ..:/workspace
